CREATE TABLE IF NOT EXISTS Usuarios (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Nome TEXT NOT NULL,
    Email TEXT NOT NULL ,
    Username TEXT NOT NULL ,
    Senha TEXT NOT NULL,
    Data DATE NOT NULL
);