apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vs-{{ .Release.Name}}
spec:
  hosts:
  - "*"
  gateways:
  - gtw
  http:
  - name: {{ .Values.aks.hostBasePath }}
    match:
    - uri:
        prefix: /{{ .Values.aks.hostBasePath }}/
    - uri:
        prefix: /{{ .Values.aks.hostBasePath }}
    rewrite:
      uri: /
    route:
    - destination:
        host: svc-{{ .Release.Name}}.{{ .Release.Namespace}}.svc.cluster.local
        port:
          number: 80    